### ISSUE TITLE
void pointer don't add/reduce

### ISSUE THREAD

**Issue by xingqing6210** [bitcraze/lps-node-firmware#30]
hi,

we see the code about:

```
const void* anchorDataPtr = &rangePacket->remoteAnchorData;
anchorDataPtr += sizeof(remoteAnchorDataFull_t);
```

or 

`return (void*)anchorDataPtr - (void*)rangePacket;`

maybe report the error
`expression must be a pointer to a complete object type`

**Comment by krichardsson** [comment]
It seems as GNU C accepts void* arithmetics (treaded as a pointer to bytes) while it is not supported by the C standard.

Thanks!
