### ISSUE TITLE
How can i update the node firmware using ubunto?

### ISSUE THREAD

**Issue by Jarlobelledo** [bitcraze/lps-node-firmware#36]
I'm getting this error.

arm-none-eabi-gcc: error: nano.specs: No such file or directory
make: *** [bin/lps-node-firmware.elf] Error 1

my Ubunto is 14.04, should I upgrade to 16 version?

**Comment by ataffanel** [comment]
If you want to be able to compile the firmware, you need the arm-embedded-gcc toolchain in your path (see https://github.com/bitcraze/lps-node-firmware#debianubuntu-linux).

This should fix the problem so I am closing the ticket, feel free to re-open if you still have problems with the compilation.
