### ISSUE TITLE
Antenna delay in TWR is wrong

### ISSUE THREAD

**Issue by krichardsson** [bitcraze/lps-node-firmware#56]
It seems as the distance measured by TWR has an offset, and this is most likely related to an error in the antenna delay. There have been some changes in libdw1000 and that might be the reason the antenna delay has changed.
The antenna delay should be re-evaluated to find a proper value

See bitcraze/crazyflie-firmware#680

**Comment by knmcguire** [comment]
The antenna delay is too depended on the orientation of the antennas as well as the environment around it, so there is no solution here that will work in any case.
